export const PERMISSIONS = {
  WORKSPACE_VIEW: 'WORKSPACE_VIEW',
  WORKSPACE_UPDATE: 'WORKSPACE_UPDATE',
  WORKSPACE_DELETE: 'WORKSPACE_DELETE',

  MEMBER_VIEW: 'MEMBER_VIEW',
  MEMBER_INVITE: 'MEMBER_INVITE',
  MEMBER_REMOVE: 'MEMBER_REMOVE',
  MEMBER_ROLE_UPDATE: 'MEMBER_ROLE_UPDATE',

  PROJECT_VIEW: 'PROJECT_VIEW',
  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_DELETE: 'PROJECT_DELETE',

  TASK_VIEW: 'TASK_VIEW',
  TASK_CREATE: 'TASK_CREATE',
  TASK_UPDATE: 'TASK_UPDATE',
  TASK_DELETE: 'TASK_DELETE',

  COMMENT_VIEW: 'COMMENT_VIEW',
  COMMENT_CREATE: 'COMMENT_CREATE',
  COMMENT_UPDATE: 'COMMENT_UPDATE',
  COMMENT_DELETE: 'COMMENT_DELETE',
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];